name: sitkpy

# Use the dev label because we will use an RC and not a
# regular release (2.0.0).
channels:
  - defaults
  - simpleitk/label/dev
  - conda-forge
  
dependencies:
  - python=3.8
  - jupyter
  - matplotlib
  - ipywidgets
  - itkwidgets
  - numpy
  - scipy
  - pandas
  - multiprocess
  - SimpleITK>1.2.4
    
